### ISSUE TITLE
Potential Minor Improvements

### ISSUE THREAD

**Issue by kavanase** [SMTG-UCL/easyunfold#10]
I had some thoughts on some potential minor improvements to the package to make it even more user-friendly, but worth discussing as I'm not sure if some/all of them are worth it:

- [x] Pulling the number of atoms and identities from the `vasprun.xml`, so that the user just needs to specify which 2 or 3 species they want to project (as in `sumo`) rather than listing the atom indices, and then done automatically from there. This would mean we could then automatically add a legend for the colour projections to the unfolded bandstructure plots which would be nice. The issue with this I guess is that currently the projections are done after the initial unfolding calculation, using the `PROCAR` file, which doesn't contain information on the atomic identities. So it would mean you also need the `vasprun.xml` at this step. In theory, the info in the `PROCAR` is also available in the `vasprun.xml`, with `pymatgen` parsers built for this, so you could add the functionality to pull this info from a `vasprun.xml` as well as from the `PROCAR`, so for these cases you could use `--atoms` and `--vasprun` instead of `--procar` and `--atoms-idx` to do the same thing (but now with a figure legend)?
    - Do you think this would be worth it @zhubonan? If so I can have a go at implementing.  
- [x] Related: Add functionality to also plot a DOS alongside the bandstructure, like in `sumo`. Could do this by having a `--dos vasprun.xml` option for the CLI plotting. If you think this would be useful @zhubonan, let me know and I can code it up!
- [x] Quick docstrings flesh-out and update to make the API docs more informative (good atm, but a quick skim through would make them extra nice and clean).
- [x] To me, the current setup of `vscale` is counter-intuitive (see https://smtg-ucl.github.io/easyunfold/cli/). It's a "scaling factor for the colour mapping", but _decreasing_ it increases the colourmap intensity, whereas intuitively as a user I would've expected the opposite behaviour. Obvs a very minor thing, but I think it would be better to reverse this behaviour?
- [x] Currently the code also supports orbital-specific projections as well as atom projections right? I think this is a useful feature and would be good to add an example showcasing this functionality. I can put together an example for this and add to the docs.

**Comment by zhubonan** [comment]
> Pulling the number of atoms and identities from the vasprun.xml, so that the user just needs to specify which 2 or 3 species they want to project (as in sumo). 

I thought about this previously, but I want to keep the dependencies light and especially not to depend on `pymatgen` (which does not use semantic versioning) to prevent potential breaking up stream changes. Perhaps a simpler approach is to parse from the POSCAR with an ad-hoc parser.

>  Related: Add functionality to also plot a DOS alongside the bandstructure, like in sumo. Could do this by having a --dos vasprun.xml option for the CLI plotting. If you think this would be useful @zhubonan, let me know and I can code it up!

This can be useful, we can make sumo an optional dependency, make two subplots call sumo to plot directly into a second axis and effective band structure in the first one? Though I guess the DOS should be from a separate SCF calculation, not that of the supercell kpoints which are not sampled using a grid. 

>  To me, the current setup of vscale is counter-intuitive (see https://smtg-ucl.github.io/easyunfold/cli/). It's a "scaling factor for the colour mapping", but decreasing it increases the colourmap intensity, whereas intuitively as a user I would've expected the opposite behaviour. Obvs a very minor thing, but I think it would be better to reverse this behaviour?

Well I think the current behaviour is fine as it is the colour range scale, so using a small scale should increase the intensity. We can rename it as `colour_scale` to make it more informative. 

>  Currently the code also supports orbital-specific projections as well as atom projections right? I think this is a useful feature and would be good to add an example showcasing this functionality. I can put together an example for this and add to the docs.

Yes, that is supported, but I have not tested it extensively. You should be able to pick out specific atoms and channel. They projection is summed all up.

**Comment by kavanase** [comment]
Ok cool! 
Good suggestion about parsing from the `POSCAR`, and about the non-uniform kpoints from the band structure calc.
I think the change to `colour_scale` and a slight modification to the help message is a good shout for that option.

**Comment by scanlond** [comment]
Agreed!

**Comment by kavanase** [comment]
This has all now been implemented and exemplified in the docs 🎉 
In #27
