### ISSUE TITLE
Rethink about the documentation system

### ISSUE THREAD

**Issue by zhubonan** [SMTG-UCL/easyunfold#15]
The project started with using mkdocs because it was simple and the site is well designed. 

As more functionalities are added, we may want to switch to Sphinx + MyST without rewriting much of the documentation files? 

The advantage is that the API documentation can be generated automatically, while currently one have to manually run commands and commit the changes.

**Comment by kavanase** [comment]
Yeah should be fairly straightforward to refactor to Sphinx. Is there much more docs functionality you want to add that isn't possible with mkdocs? (Like tutorial notebooks I guess?)

**Comment by zhubonan** [comment]
Yes the notebooks for showing the Python APIs for example. Also one no longer needs to manually update the API docs. The latter can be automated with GitHub actions but the files still need to be added as source I think.

**Comment by zhubonan** [comment]
Addressed by #17
