### ISSUE TITLE
styling the plot using `mplstyle` file

### ISSUE THREAD

**Issue by zhubonan** [SMTG-UCL/easyunfold#6]
Syle of the plots may be further adjusted by `mplstyle` file. 
Should be easy to implemented. `sumo` has something similar. 

Note that `mplstyle` file does changes globally, so caution is needed for interactive sessions (notebooks etc.)

**Comment by zhubonan** [comment]
This should be used only for the CLI as loading `mplstyle` changes global settings in an interactive python session which is not ideal.

**Comment by kavanase** [comment]
This would be quite a useful feature!

**Comment by kavanase** [comment]
Closing this issue as now implemented 🙌
